create table account (
    id            bigint generated by default as identity primary key,
    name          varchar(255) not null,
    currency      varchar(3)   not null,
    account_type  varchar(20)  not null,
    posting_count bigint       not null default 0,
    version       bigint       not null default 0
);

create table journal_entry (
    id          bigint generated by default as identity primary key,
    description  varchar(500),
    currency     varchar(3)   not null,
    posted_at    timestamptz  not null
);

create table journal_line (
    id         bigint generated by default as identity primary key,
    entry_id   bigint         not null references journal_entry (id),
    account_id bigint         not null references account (id),
    amount     numeric(19, 4) not null
);

create index idx_journal_line_account on journal_line (account_id);

create table idempotency_key (
    idem_key         varchar(255) primary key,
    journal_entry_id bigint      not null references journal_entry (id),
    created_at       timestamptz not null
);
